# Current Version: 1.0.0

name: Build & Push hezhijie0327/ZJDNSServer

on:
    schedule:
        - cron: "0 0 1 * *"
    workflow_dispatch:

jobs:
    build-package-zjdns:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v4
            - name: Step 2 - Set up QEMU
              uses: docker/setup-qemu-action@v3
              with:
                image: tonistiigi/binfmt:master
            - name: Step 3 - Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Step 4 - Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Step 5 - Login to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ secrets.GHCR_USERNAME }}
                  password: ${{ secrets.GHCR_TOKEN }}
            - name: Step 6 - Build cloudflareddns:latest
              uses: docker/build-push-action@v5
              with:
                  file: ./Dockerfile
                  platforms: linux/amd64, linux/arm64
                  push: true
                  tags: |
                      hezhijie0327/zjdns:latest
                      ghcr.io/hezhijie0327/zjdns:latest
